[project]
name = "titanic"
version = "0.1.0"
requires-python = ">=3.9"
dependencies = [
    "lightgbm>=4.6.0",
    "pandas>=2.2.3",
    "polars>=1.30.0",
    "pyarrow>=20.0.0",
    "scikit-learn>=1.6.1",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
    "kaggle>=1.7.4.5",
]
